resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
<<<<<<< HEAD
  newName: faingershran/cp
  newTag: 1.0.3
=======
  newName: danateam/container-app-operator
  newTag: latest
>>>>>>> d0c06005e9644db890b7358c1628ada5c21ecd7a
