version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.19.6

    steps:
      - checkout

      - run:
          name: Run tests
          command: go test ./...

  build:
    docker:
      - image: circleci/golang:1.19.6

    steps:
      - checkout

      - run:
          name: Build Go application
          command: go build ./...

  publish:
    docker:
      - image: docker:stable

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build and push Docker image
          command: |
            docker build -t danateam/container-app-operator:latest .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD danateam
            docker push danateam/container-app-operator:latest

workflows:
  version: 2.1
  build-and-publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
