# permissions for end users to edit capprevisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: capprevision-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: container-app-operator
    app.kubernetes.io/part-of: container-app-operator
    app.kubernetes.io/managed-by: kustomize
  name: capprevision-editor-role
rules:
- apiGroups:
  - rcs.dana.io
  resources:
  - capprevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rcs.dana.io
  resources:
  - capprevisions/status
  verbs:
  - get
