apiVersion: rcs.dana.io/v1alpha1
kind: Capp
metadata:
  name: capp-example
spec:
  configurationSpec:
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: ENV
            value: prep
          - name: APP
            value: my-application
          envFrom:
          - secretRef:
            name: test-secret
          image: example-python-app:v1
          name: my-application
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
                httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3
  routeSpec:
    hostname: example.com
    HTTPS: true
  scaleMetric: rps
