apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "container-app-operator.fullname" . }}-capprevision-viewer-role
  labels:
    {{- include "container-app-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rcs.dana.io
  resources:
  - capprevisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rcs.dana.io
  resources:
  - capprevisions/status
  verbs:
  - get