apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dnsConfig.name }}
  labels:
    {{- include "container-app-operator.labels" . | nindent 4 }}
data:
  zone: "{{ .Values.dnsConfig.zone }}"
  cname: "{{ .Values.dnsConfig.cname }}"