apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-app-operator.fullname" . }}-metrics-service
  labels:
    {{- include "container-app-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.httpsPort }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    control-plane: controller-manager